Ft/planetbase
Planetbase-io/planetbase pull request #8
Opened 2022-09-22 21:51 UTC by temycodes

2022-09-22 22:03 UTC, Daniel-16 requested changes
Pls change the background image or color when fetching events. 
![Screenshot_20220922-230135](https://user-images.githubusercontent.com/52180799/191859402-bb9ad9c1-9ca8-4bae-b6e7-4787df2900e9.png)

2022-09-22 23:42 UTC, Daniel-16 commented
I'm still waiting to see your changes @temycodes

2022-09-23 00:04 UTC, temycodes commented
okay, Dan... on it

2022-09-23 00:51 UTC, Daniel-16 approved these changes

2022-09-23 00:52 UTC, merged